version: '3.8'

services:
  buns-chat-api:
    image: buns_chat_api:1.0.0
    container_name: buns-chat-api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - SearchHubSettings__Url=http://buns-search-api-balancer:9090/hub/bun/search
      - SearchStreamingHubSettings__Url=http://buns-search-api-balancer:9090/hub/bun/streaming_search
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - buns-public-net
    depends_on:
      - nginx-balancer
        
  nginx-balancer:
    image: nginx:latest
    container_name: buns-search-api-balancer
    ports:
      - "9090:9090"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - buns-public-net
      - buns-internal-net
    depends_on:
      - buns-search-api-1
      - buns-search-api-2
      - buns-search-api-3
        
  buns-search-api-1:
    image: buns_search_api:1.0.0
    container_name: buns-search-api-1
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:9090
      - OllamaApiSettings__Url=http://ollama:11434/api/generate
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9090/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - buns-internal-net
      - ollama-net
    depends_on:
      - ollama
        
  buns-search-api-2:
    image: buns_search_api:1.0.0
    container_name: buns-search-api-2
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:9090
      - OllamaApiSettings__Url=http://ollama:11434/api/generate
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9090/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - buns-internal-net
      - ollama-net
    depends_on:
      - ollama
        
  buns-search-api-3:
    image: buns_search_api:1.0.0
    container_name: buns-search-api-3
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:9090
      - OllamaApiSettings__Url=http://ollama:11434/api/generate
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9090/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - buns-internal-net
      - ollama-net
    depends_on:
      - ollama
    
  ollama:
    image: ollama/ollama
    container_name: ollama-llm
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    networks:
      - ollama-net

volumes:
  ollama_data:

networks:
  buns-public-net:
    driver: bridge
  buns-internal-net:
    driver: bridge
  ollama-net:
    driver: bridge